from retriever import CrosswordDataRetriever
from crosswordGUI import CrosswordGUI

#crosswordData = {'clues': {'across': [{'id': '1', 'text': '"That hits the spot!"'}, {'id': '4', 'text': '"Scooby-Doo" character who wears an orange turtleneck'}, {'id': '6', 'text': 'Wild party, slangily'}, {'id': '7', 'text': "Company's public perception"}, {'id': '8', 'text': 'Word seen on money, or in "money"'}], 'down': [{'id': '1', 'text': 'Pond plants'}, {'id': '2', 'text': 'Prayer ending'}, {'id': '3', 'text': 'Like diamonds and double-black diamond ski runs'}, {'id': '4', 'text': 'Alternative to Airbnb'}, {'id': '5', 'text': 'Make, as money'}]}, 'cells': {0: {'block': True, 'text': '', 'number': ''}, 1: {'block': True, 'text': '', 'number': ''}, 2: {'block': False, 'text': 'A', 'number': '1'}, 3: {'block': False, 'text': 'A', 'number': '2'}, 4: {'block': False, 'text': 'H', 'number': '3'}, 5: {'block': False, 'text': 'V', 'number': '4'}, 6: {'block': False, 'text': 'E', 'number': '5'}, 7: {'block': False, 'text': 'L', 'number': ''}, 8: {'block': False, 'text': 'M', 'number': ''}, 9: {'block': False, 'text': 'A', 'number': ''}, 10: {'block': False, 'text': 'R', 'number': '6'}, 11: {'block': False, 'text': 'A', 'number': ''}, 12: {'block': False, 'text': 'G', 'number': ''}, 13: {'block': False, 'text': 'E', 'number': ''}, 14: {'block': False, 'text': 'R', 'number': ''}, 15: {'block': False, 'text': 'B', 'number': '7'}, 16: {'block': False, 'text': 'R', 'number': ''}, 17: {'block': False, 'text': 'A', 'number': ''}, 18: {'block': False, 'text': 'N', 'number': ''}, 19: {'block': False, 'text': 'D', 'number': ''}, 20: {'block': False, 'text': 'O', 'number': '8'}, 21: {'block': False, 'text': 'N', 'number': ''}, 22: {'block': False, 'text': 'E', 'number': ''}, 23: {'block': True, 'text': '', 'number': ''}, 24: {'block': True, 'text': '', 'number': ''}}}
#crosswordData = {'clues': {'across': [{'id': '1', 'text': 'The slightest amount'}, {'id': '5', 'text': 'Airport boarding area'}, {'id': '6', 'text': 'Eye, ear or heart'}, {'id': '7', 'text': 'Fishing line spool'}, {'id': '8', 'text': 'Depend (upon)'}], 'down': [{'id': '1', 'text': 'Feel the same way'}, {'id': '2', 'text': 'Roll with a hole'}, {'id': '3', 'text': 'Country where Elizabeth Gilbert goes to eat in "Eat, Pray, Love"'}, {'id': '4', 'text': "Prime minister's address on Downing Street"}, {'id': '6', 'text': 'Hockey legend Bobby'}]}, 'cells': {0: {'block': True, 'text': '', 'number': ''}, 1: {'block': False, 'text': 'A', 'number': '1'}, 2: {'block': False, 'text': 'B', 'number': '2'}, 3: {'block': False, 'text': 'I', 'number': '3'}, 4: {'block': False, 'text': 'T', 'number': '4'}, 5: {'block': True, 'text': '', 'number': ''}, 6: {'block': False, 'text': 'G', 'number': '5'}, 7: {'block': False, 'text': 'A', 'number': ''}, 8: {'block': False, 'text': 'T', 'number': ''}, 9: {'block': False, 'text': 'E', 'number': ''}, 10: {'block': False, 'text': 'O', 'number': '6'}, 11: {'block': False, 'text': 'R', 'number': ''}, 12: {'block': False, 'text': 'G', 'number': ''}, 13: {'block': False, 'text': 'A', 'number': ''}, 14: {'block': False, 'text': 'N', 'number': ''}, 15: {'block': False, 'text': 'R', 'number': '7'}, 16: {'block': False, 'text': 'E', 'number': ''}, 17: {'block': False, 'text': 'E', 'number': ''}, 18: {'block': False, 'text': 'L', 'number': ''}, 19: {'block': True, 'text': '', 'number': ''}, 20: {'block': False, 'text': 'R', 'number': '8'}, 21: {'block': False, 'text': 'E', 'number': ''}, 22: {'block': False, 'text': 'L', 'number': ''}, 23: {'block': False, 'text': 'Y', 'number': ''}, 24: {'block': True, 'text': '', 'number': ''}}}

crosswordData = CrosswordDataRetriever().retrieve_crossword();
#print( "Data:\n", crosswordData)

gui = CrosswordGUI( retData = crosswordData)
